name: K3S Deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download VM IP
      uses: actions/download-artifact@v3
      with:
        name: vm-ip
        path: .

    - name: Load VM IP
      run: echo "VM_IP=$(cat vm_ip.txt)" >> $GITHUB_ENV

    - name: Deploy K3S via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "Saving SSH private key..."
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        echo "Copying K3S installation script to the server..."
        scp -i private_key.pem -o StrictHostKeyChecking=no scripts/install_k3s.sh root@$VM_IP:/root/

        echo "Executing K3S installation script..."
        ssh -i private_key.pem -o StrictHostKeyChecking=no root@$VM_IP "chmod +x /root/install_k3s.sh && sudo /root/install_k3s.sh"
