---
- name: Common Setup for All Nodes
  hosts: k3s_cluster
  become: true
  roles:
    - role: common

- name: Setup K3S Master Node(s)
  hosts: masters
  become: true
  roles:
    - role: k3s-master

- name: Setup K3S Worker Node(s)
  hosts: workers
  become: true
  roles:
    - role: k3s-worker