name: Deploy K3S Cluster on Hetzner Cloud

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      master_nodes:
        description: 'Number of master nodes'
        required: false
        default: '1'
        type: string
      worker_nodes:
        description: 'Number of worker nodes'
        required: false
        default: '1'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/get-kubeconfig.sh
          chmod +x scripts/generate-inventory.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="hcloud_token=${{ secrets.HCLOUD_TOKEN }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var="ssh_private_key_path=~/.ssh/id_rsa" \
            -var="master_node_count=${{ github.event.inputs.master_nodes }}" \
            -var="worker_node_count=${{ github.event.inputs.worker_nodes }}"
        if: github.event.inputs.action == 'apply'

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
            -var="hcloud_token=${{ secrets.HCLOUD_TOKEN }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var="ssh_private_key_path=~/.ssh/id_rsa" \
            -var="master_node_count=${{ github.event.inputs.master_nodes }}" \
            -var="worker_node_count=${{ github.event.inputs.worker_nodes }}"
        if: github.event.inputs.action == 'apply'

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve \
            -var="hcloud_token=${{ secrets.HCLOUD_TOKEN }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="ssh_private_key_path=~/.ssh/id_rsa"
        if: github.event.inputs.action == 'destroy'

      - name: Get Cluster Info
        working-directory: ./terraform
        run: |
          if [ -f .terraform.lock.hcl ]; then
            echo "CLUSTER INFO:"
            terraform output
          fi
        if: github.event.inputs.action == 'apply'

      - name: Archive kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: .kube/config-k3s-cluster
        if: github.event.inputs.action == 'apply'