name: K3S Deployment in Hetzner Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "HCLOUD_TOKEN length: $(echo -n "${{ secrets.HCLOUD_TOKEN }}" | wc -c)"
          echo "SSH_PUBLIC_KEY length: $(echo -n "${{ secrets.SSH_PUBLIC_KEY }}" | wc -c)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform Deployment
        working-directory: terraform
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform plan -var="hcloud_token=$HCLOUD_TOKEN" -var="ssh_public_key=$SSH_PUBLIC_KEY" -out main.tfplan

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/main.tfplan

  apply:
    needs: terraform
    runs-on: ubuntu-latest
    environment: terraform-apply

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform (if needed)
        working-directory: terraform
        run: |
          if [ ! -d ".terraform" ]; then
            terraform init
          fi

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Apply Terraform Configuration
        working-directory: terraform
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve "main.tfplan"

  # deploy-k3s:
  #   needs: deploy-infrastructure
  #   uses: ./.github/workflows/k3s-deploy.yml
