name: Terraform Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "TEST_TOKEN Length: $(echo -n "${{ secrets.TEST_TOKEN }}" | wc -c)"
          echo "HCLOUD_TOKEN Length: $(echo -n "${{ secrets.HCLOUD_TOKEN }}" | wc -c)"
          echo "SSH_PUBLIC_KEY Length: $(echo -n "${{ secrets.SSH_PUBLIC_KEY }}" | wc -c)"
          echo "NON_TOKEN Length: $(echo -n "${{ secrets.NON_TOKEN }}" | wc -c)"
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          NON_TOKEN: ${{ secrets.NON_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Plan Terraform Deployment
        working-directory: terraform
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          export exitcode=0
          terraform plan \
            -var hcloud_token=$HCLOUD_TOKEN \
            -var ssh_public_key=$SSH_PUBLIC_KEY \
            -out main.tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo "Error: Terraform plan failed"
            exit 1
          else
            echo "Terraform plan was successful"
            exit 0
          fi

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/main.tfplan       

  terraform-apply:
    needs: terraform-plan
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve "./main.tfplan"

  # apply:
  #   name: 'Terraform apply'
  #   needs: plan
  #   runs-on: ubuntu-latest
  #   environment: terraform-apply

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3

  #   - name: Setup Terraform
  #     uses: hashicorp/setup-terraform@v2
  #     with:
  #       terraform_version: 1.5.6

  #   - name: Initialize Terraform
  #     working-directory: terraform
  #     run: terraform init

  #   - name: Apply Terraform Configuration
  #     working-directory: terraform
  #     run: |
  #       terraform apply -auto-approve
    
